#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 总包test
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="总包test")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insert总包test明细(总包test明细 instance);
    partial void Update总包test明细(总包test明细 instance);
    partial void Delete总包test明细(总包test明细 instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::总包test.Properties.Settings.Default.总包testConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<总包test> 总包test
		{
			get
			{
				return this.GetTable<总包test>();
			}
		}
		
		public System.Data.Linq.Table<总包test明细> 总包test明细
		{
			get
			{
				return this.GetTable<总包test明细>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.总包test")]
	public partial class 总包test
	{
		
		private string _项目;
		
		private System.Nullable<double> _开票金额;
		
		private System.Nullable<double> _收款金额;
		
		private System.Nullable<double> _收票金额;
		
		private System.Nullable<double> _付款金额;
		
		public 总包test()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_项目", DbType="VarChar(50)")]
		public string 项目
		{
			get
			{
				return this._项目;
			}
			set
			{
				if ((this._项目 != value))
				{
					this._项目 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_开票金额", DbType="Float")]
		public System.Nullable<double> 开票金额
		{
			get
			{
				return this._开票金额;
			}
			set
			{
				if ((this._开票金额 != value))
				{
					this._开票金额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_收款金额", DbType="Float")]
		public System.Nullable<double> 收款金额
		{
			get
			{
				return this._收款金额;
			}
			set
			{
				if ((this._收款金额 != value))
				{
					this._收款金额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_收票金额", DbType="Float")]
		public System.Nullable<double> 收票金额
		{
			get
			{
				return this._收票金额;
			}
			set
			{
				if ((this._收票金额 != value))
				{
					this._收票金额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_付款金额", DbType="Float")]
		public System.Nullable<double> 付款金额
		{
			get
			{
				return this._付款金额;
			}
			set
			{
				if ((this._付款金额 != value))
				{
					this._付款金额 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.总包test明细")]
	public partial class 总包test明细 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _编号;
		
		private string _项目;
		
		private System.Nullable<double> _开票金额;
		
		private System.Nullable<double> _收款金额;
		
		private System.Nullable<double> _收票金额;
		
		private System.Nullable<double> _付款金额;
		
		private System.Nullable<System.DateTime> _日期;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On编号Changing(int value);
    partial void On编号Changed();
    partial void On项目Changing(string value);
    partial void On项目Changed();
    partial void On开票金额Changing(System.Nullable<double> value);
    partial void On开票金额Changed();
    partial void On收款金额Changing(System.Nullable<double> value);
    partial void On收款金额Changed();
    partial void On收票金额Changing(System.Nullable<double> value);
    partial void On收票金额Changed();
    partial void On付款金额Changing(System.Nullable<double> value);
    partial void On付款金额Changed();
    partial void On日期Changing(System.Nullable<System.DateTime> value);
    partial void On日期Changed();
    #endregion
		
		public 总包test明细()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_编号", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int 编号
		{
			get
			{
				return this._编号;
			}
			set
			{
				if ((this._编号 != value))
				{
					this.On编号Changing(value);
					this.SendPropertyChanging();
					this._编号 = value;
					this.SendPropertyChanged("编号");
					this.On编号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_项目", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 项目
		{
			get
			{
				return this._项目;
			}
			set
			{
				if ((this._项目 != value))
				{
					this.On项目Changing(value);
					this.SendPropertyChanging();
					this._项目 = value;
					this.SendPropertyChanged("项目");
					this.On项目Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_开票金额", DbType="Float")]
		public System.Nullable<double> 开票金额
		{
			get
			{
				return this._开票金额;
			}
			set
			{
				if ((this._开票金额 != value))
				{
					this.On开票金额Changing(value);
					this.SendPropertyChanging();
					this._开票金额 = value;
					this.SendPropertyChanged("开票金额");
					this.On开票金额Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_收款金额", DbType="Float")]
		public System.Nullable<double> 收款金额
		{
			get
			{
				return this._收款金额;
			}
			set
			{
				if ((this._收款金额 != value))
				{
					this.On收款金额Changing(value);
					this.SendPropertyChanging();
					this._收款金额 = value;
					this.SendPropertyChanged("收款金额");
					this.On收款金额Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_收票金额", DbType="Float")]
		public System.Nullable<double> 收票金额
		{
			get
			{
				return this._收票金额;
			}
			set
			{
				if ((this._收票金额 != value))
				{
					this.On收票金额Changing(value);
					this.SendPropertyChanging();
					this._收票金额 = value;
					this.SendPropertyChanged("收票金额");
					this.On收票金额Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_付款金额", DbType="Float")]
		public System.Nullable<double> 付款金额
		{
			get
			{
				return this._付款金额;
			}
			set
			{
				if ((this._付款金额 != value))
				{
					this.On付款金额Changing(value);
					this.SendPropertyChanging();
					this._付款金额 = value;
					this.SendPropertyChanged("付款金额");
					this.On付款金额Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_日期", DbType="Date")]
		public System.Nullable<System.DateTime> 日期
		{
			get
			{
				return this._日期;
			}
			set
			{
				if ((this._日期 != value))
				{
					this.On日期Changing(value);
					this.SendPropertyChanging();
					this._日期 = value;
					this.SendPropertyChanged("日期");
					this.On日期Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
